version: "3.8"

name: pornspot-ai

services:
  localstack:
    image: localstack/localstack:3.2.0
    container_name: pornspot-local-aws
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      # - DEBUG=1 # uncomment for verbose logs
      - SERVICES=s3,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local-network

volumes:
  localstack_data:

networks:
  local-network:
    driver: bridge
