version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "pornspot-ai-dev"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
resolve_image_repos = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-dev"

[default.package]
[default.package.parameters]
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.global]
[dev.global.parameters]
stack_name = "pornspot-ai-dev"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
resolve_image_repos = true

[dev.deploy]
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-dev"

[stage]
[stage.global]
[stage.global.parameters]
stack_name = "pornspot-ai-stage"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=stage"
resolve_image_repos = true

[stage.deploy]
[stage.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-stage"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "pornspot-ai-prod"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
resolve_image_repos = true

[prod.deploy]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-prod"