version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "pornspot-ai-dev"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-dev"

[default.package]
[default.package.parameters]
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.global]
[dev.global.parameters]
stack_name = "pornspot-ai-dev"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true

[dev.deploy]
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-dev"

[stage]
[stage.global]
[stage.global.parameters]
stack_name = "pornspot-ai-stage"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
parameter_overrides = "Environment=stage CdnCertificateArn=arn:aws:acm:us-east-1:688567299790:certificate/3dd24826-cf6e-4719-9c93-6d95b87d897c"

[stage.deploy]
[stage.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-stage"
parameter_overrides = "Environment=stage CdnCertificateArn=arn:aws:acm:us-east-1:688567299790:certificate/3dd24826-cf6e-4719-9c93-6d95b87d897c"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "pornspot-ai-prod"
s3_bucket = "pornspot-sam-deployments"
s3_prefix = "pornspot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
parameter_overrides = "Environment=prod CdnCertificateArn=arn:aws:acm:us-east-1:688567299790:certificate/89e05297-5b59-41c6-8d0e-e5774f1d09b7"

[prod.deploy]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "pornspot-ai-prod"
parameter_overrides = "Environment=prod CdnCertificateArn=arn:aws:acm:us-east-1:688567299790:certificate/89e05297-5b59-41c6-8d0e-e5774f1d09b7"